config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "utilities#index"

  resources :users do 
    resources :utilities, only: [:index, :new, :create, :show]
    resources :payments, only: [:index, :show, :new, :create]
  end
  
  get '/home',to: 'homes#home' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :utility_payments
  has_many :utilities, through: :utility_payments
  validates :name, presence: true
  validates :amount, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  :confirmable

  has_many :utilities
  has_many :payments

  has_one_attached :avatar

  validates :name, presence: true
end

app/models/utility.rb
class Utility < ApplicationRecord
  belongs_to :user
  has_many :utility_payments
  has_many :payments, through: :utility_payments

  has_one_attached :icon
  validates :name, presence: true
end

app/models/utility_payment.rb
class UtilityPayment < ApplicationRecord
  belongs_to :utility
  belongs_to :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home]
  before_action :redirect_to_home_path

  private

  def redirect_to_home_path
    home_path unless user_signed_in?
  end

  def after_sign_out_path_for(_resource_or_scope)
    home_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password password_confirmation avatar])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation avatar])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def show
    @utility = Utility.find(params[:utility_id])
    @payment = @utility.payments.find(params[:id])
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = current_user.payments.new(payment_params)
    if @payment.save
      redirect_to root_path,
                  notice: 'Payment was successfully created'
    else
      render :new, alert: 'Payment could not be created'
    end
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, utility_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
  def index
    @user = current_user
    @utilities = @user.utilities.includes(icon_attachment: :blob).all
  end

  def new
    @utility = Utility.new
  end

  def show
    @utility = Utility.find(params[:id])
    @payments = @utility.payments.all
  end

  def create
    @utility = current_user.utilities.create!(utility_params)
    if @utility.save
      redirect_to user_utilities_path(user_id: current_user.id), notic: 'Utility Item Saved Successfully'
    else
      rended :new, alert: "Couldn't save the utility"
    end
  end

  def utility_params
    params.require(:utility).permit(:name, :icon)
  end
end

app/controllers/utility_payments_controller.rb
class UtilityPaymentsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user, size = 30)
    if user.avatar.attached?
      user.avatar.representation(resize_to_limit: [size, size])
      # user.avatar.url
    else
      'defualt-avatar.png'
    end
  end

  def utility_icon(utility, size)
    if utility.icon.attached?
      utility.icon.representation(resize_to_limit: [size, size])
      # utility.icon.url
    else
      utility.icon.attach_icon = 'default_icon.png'
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/homes/home.html.erb
<section class="splash"> 
  <div class="splash--left">
    <h1>Welcome to BillPay</h1>
  </div>

  <div class="splash--right">   
    <div class="splash__logo">
        <div class="logo-icon"> <i class="fa-solid fa-people-roof "></i> </div>
        <h1 class="text"><strong>Pay</strong>Bill</h2>
    </div>   
    
    <%= link_to "Login", new_user_session_path, class:"btn btn--blue btn--login"%>
    <%= link_to "Signup", new_user_registration_path, class:'btn btn--link btn--link--1' %> 
  </div>  
</section>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UtilityPaymentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbo-visit-control" content="reload">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render partial: "shared/desktop_nav" %> 
   <div class = "flash" >
      <%= render "shared/flash" %>
    </div>    

    <%= yield %>

  </body>
</html>

app/views/payments/_header.html.erb
<ul class="header">
  <li class="nav-item">
    <%= link_to user_utilities_path, class: "back-link" do %>
      <i class="fa-solid fa-arrow-left-long back"></i>
    <%end%>
  </li>
  <li class="nav-item"><%= name %></li>
  <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn-header" %>
  </li>
</ul>

app/views/payments/new.html.erb
<%= render "header", name: "NEW TRANSACTION" %>
<%= form_with model: @payment, url: user_payments_path, class: "form" do |f| %>
  <div class="field form__group first">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form__input", placeholder: "Transaction name" %>
  </div>
  <div class="field form__group">
    <%= f.label :amount, class: "form-label" %><br>
    <%= f.number_field :amount, step: :any, class: "form__input", placeholder: "Transaction amount"%>
  </div>
  <h2>Category Type: </h2>
  
   <div class="field checkbox-group">
      <%= f.collection_check_boxes(:utility_ids, Utility.where(user_id: current_user.id), :id, :name,{multiple: true} , class: "form__checkbox") do |b| %>
          <%= b.label class:"label-checkbox" do%>
          <%= b.check_box + b.text%>
          <%end %>
      <% end %>
    </div>   

  <div class="actions">
    <%= f.submit "Add Transaction", class: "btn btn--blue center" %>
  </div>
<% end %>

app/views/payments/show.html.erb
<%= render "header", name: @payment.name %>
<div>
  <section class="payment-detail">
    <div class="payment-detail--header">
      <div class="utility-type" >
        <%= image_tag utility_icon(@utility, 40), class: "icon" %>
        <p> <%= @utility.name %> PAYMENT</p>
      </div>
      <hr />
      <div class="detail">
        <div class="type">
          <p>Payment Type: </p>
          <span><%=  @payment.name %></span>
        </div>
        <div class="amount">
          <p>Payment Amount: </p>
          <span><%=  @payment.amount %></span>
        </div>
        <div class="date">
          <p>Date: </p>
          <span><%=  @payment.created_at.strftime("Transaction made on %B %d, %Y @ %I:%M%p")  %></span>
        </div>
      </div>
    </div>
  </section>

app/views/shared/_desktop_nav.html.erb
<% if user_signed_in? %>
  <nav class="desktop-navbar" >
    <div class="splash-logo">
      <div class="logo-header"> <i class="fa-solid fa-people-roof "></i> </div>
      <h1 class="logo-text"><strong>Pay</strong>Bill</h2>
    </div>
    <ul class="nav-items">
      <div class="list">
        <div class="col-left">
          <li class="nav-item">
            <%= link_to  user_utilities_path(user_id: current_user.id), class: "nav-link" do %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Home", user_utilities_path(user_id: current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", user_utilities_path(user_id: current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        </div>
        <div class="col-right">
          <li class="nav-item nav-signout">
            <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>
          </li>
          <div class="nav-header">
            <%= image_tag user_avatar(current_user, 100), class:"user-avatar" %>
          </div>
        </ul>
      </nav>
    <% end %>

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message" 
      data-controller = "removals" 
      data-action="animationend -> removals#remove"> 
    <%= message %> 
  </div>
<% end %>

app/views/shared/_header.html.erb
 
  <ul class="header">
    <li class="nav-item">       
      <button class="btn-open"> 
         <i class="fa-solid fa-bars fa-4x back"></i>
      </button>
     
    </li>
    <li class="nav-item"><%= name %></li>
    <li class="nav-item">    
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn-header" %>
    </li>
  </ul>

    <%= javascript_include_tag "navbar", defer: true, cache: true %>

  

app/views/shared/_navbar.html.erb
<nav class="navbar" >
  <button class="btn-close" >
    <i class="fa-solid fa-xmark fa-2x"></i>
  </button>
  <div class="nav-header">
    <%= image_tag user_avatar(current_user, 100), class:"user-avatar" %>
    <span><%= current_user.name %> </span>
  </>
  <hr  />
</div>
<ul class="nav-items">
  <li class="nav-item">
    <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Categories", user_utilities_path(user_id: current_user.id), class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>
  </li>
</ul>
</nav>
<%= javascript_include_tag "navbar", defer: true, cache: true %>

app/views/shared/_signup_header.erb
<nav class="desktop-navbar" >
  <div class="splash-logo">
    <div class="logo-header"> <i class="fa-solid fa-people-roof "></i> </div>
    <h1 class="logo-text"><strong>Pay</strong>Bill</h2>
  </div>
  <ul class="nav-items">
   
    <div class="list">        
      <li class="nav-item">
       <% if request.fullpath == "/users/sign_in" %>
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        <% end %>
      </li>
      <% if request.fullpath == "/users/sign_up" %>
      <li class="nav-item nav-signout">
        <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </div>   
  </ul>        
</nav>
  

app/views/shared/header1.html.erb
<ul class="header">
  <li class="nav-item">
    <%= link_to user_utilities_path(user_id: current_user.id) do %>
      <i class="fa-solid fa-arrow-left-long back"></i>
    <%end%>
  </li>
  <li class="nav-item"><%= name %></li>
  <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn-header" %>
  </li>
</ul>

app/views/users/index.html.erb
<%= image_tag user_avatar(current_user, 100)%>

app/views/utilities/_category.html.erb
<%@utilities.each do |utility|%>
  <%= link_to user_utility_path(user_id: current_user.id, id: utility.id), id: utility.id do %>
    <div class="utility">
      <%= image_tag utility_icon(utility, 200), class: "icon" %>
      <div class="utility__detail">
        <p class="utility__name" > <%= utility.name %> </p>
        <p class="utility__badge" > <%= utility.utility_payments.count %> </p>
      </div>
    </div>
  <%end%>
<%end%>

app/views/utilities/_category_item.html.erb
<%@payments.each do |payment|%>
  <%= link_to user_payment_path(user_id: current_user.id,utility_id: @utility.id, id: payment.id) do %>
    <div class="payment">
      <%= image_tag utility_icon(@utility, 200), class: "icon" %>
      <div class="payment__detail">
        <p class="payment__name" ><strong> <%= payment.name %> </strong> </p>
        <p class="payment__date" > <%= payment.created_at.strftime("%B %d, %Y") %> </p>
      </div>
      <p> $ <%= payment.amount %> </p>
    </div>
  <%end%>
<%end%>

app/views/utilities/_header.html.erb
<ul class="header">
  <li class="nav-item">
    <%= link_to user_utilities_path(user_id: current_user.id), class: "back-link" do %>
      <i class="fa-solid fa-arrow-left-long back"></i>
    <%end%>
  </li>
  <li class="nav-item"><%= name %></li>
  <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn-header" %>
  </li>
</ul>

app/views/utilities/index.html.erb
<%= render "shared/header", name: "Categories" %>
<%= render "shared/navbar" %>
<div class="header-2">
  Hi, <strong>
    <%= current_user.name %>
  </strong>
</div>
<div class="utilities">
  <%= render partial: 'category' %>
</div>
<div class="utilities-footer">
  <%= link_to "New Utility", new_user_utility_path(user_id: current_user.id), class: "btn btn--green" %>
  <div>

app/views/utilities/new.html.erb
<%= render "header", name: "NEW CATEGORY" %>
<%= form_with model: @utility, url: user_utilities_path, class: "form" do |f| %>
  <div class="field form__group first file_upload">
    <div class="row">
      <%= image_tag utility_icon(@utility, 100), class: "icon" %>
      <div class="btn btn-image">
        <i class="fa-solid fa-upload"></i>  Upload
        <%= f.file_field :icon %>
      </div>
    </div>
  </div>
  <div class="field form__group first">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form__input", placeholder:"Category name" %>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn--blue" %>
  </div>
<% end %>

app/views/utilities/show.html.erb
<%= render "header", name: @utility.name %>
<div class="header-2">
  Hi, <strong>
    <%= current_user.name %>
  </strong>
</div>
<section class="utility-detail">
  <div class="payments">
    <%= render partial:"category_item" %>
  </div>
</section>
<div class="utilities-footer">
  <%= link_to "New Transactions", new_user_payment_path(user_id: current_user.id), class: "btn btn--green" %>
  <div>